SELECT TOP (1000) [DateID]
      ,[QuoteID]
      ,[ClientID]
      ,[Sales]
      ,[SumInsured]
      ,[Quotes]
      ,[ARRA]
      ,[Brand]
      ,[ProductType]
      ,[Gender]
      ,[IsSmoker]
      ,[Suburb]
      ,[State]
      ,[PostCode]
      ,[Section]
      ,[Question]
      ,[AnswerValue]
      ,[Occupation]
      ,[Age]
      ,[DeclineReason]
      ,[UWAppStatus]
      ,[QuestionSetInstanceStatus]
      ,[UserID]
      ,[TeamName]
      ,[IsDecline]
      ,[IsCurrent]
  FROM [EvolveKPI].[dbo].[tblMaster_CIP]