import streamlit as st

st.title("Help & FAQs")

faqs = [
    {
        "question": "What is the Customer Insight Chatbot?",
        "answer": "The Customer Insight Chatbot is an AI-powered assistant designed to help you analyze, query, and interpret customer, sales, and call transcription data for business intelligence and reporting."
    },
    {
        "question": "What data sources are available?",
        "answer": "The platform provides access to SQL data (from January 2022 to May 2025) and call transcription data (from October 2024 to March 2025)."
    },
    {
        "question": "How do I log in?",
        "answer": "Use your registered email and password. If you have trouble logging in, ensure your credentials are correct or contact your administrator."
    },
    {
        "question": "What can I ask the chatbot?",
        "answer": "You can ask for sales insights, customer trends, gender/smoker-based analytics, call summaries, and more. The chatbot can also interpret and summarize SQL and transcription data."
    },
    {
        "question": "How is my session data stored?",
        "answer": "Session data, including chat history, is securely stored in our databases. Your session is updated each time you interact with the chatbot."
    },
    {
        "question": "How are user credentials managed?",
        "answer": "User credentials are managed securely in Azure Cosmos DB. Passwords are stored in hashed format."
    },
    {
        "question": "What is the SQL Agent Disclaimer?",
        "answer": "The SQL Agent uses data from January 2022 to May 2025. Results outside this range are not available."
    },
    {
        "question": "What is the Transcription Agent Disclaimer?",
        "answer": "The Transcription Agent uses data from October 2024 to March 2025. Results outside this range are not available."
    },
    {
        "question": "How do I log out?",
        "answer": "Use the 'Logout' button in the sidebar to securely end your session."
    },
    {
        "question": "How are insights formatted?",
        "answer": "All insights and summaries are formatted in executive-level Markdown, suitable for business reporting and dashboards."
    },
    {
        "question": "Who can I contact for support?",
        "answer": "Contact your system administrator or the project owner for technical support or access issues."
    },
    {
        "question": "Can I see the raw SQL or transcription data?",
        "answer": "We are unable to provide direct access to the underlying raw SQL database or transcription data due to privacy and compliance reasons. Please use the chatbot to request summaries, insights, or analytics instead."
    },
    {
        "question": "Can I download or export the data?",
        "answer": "For security and compliance, direct download or export of the raw data is not permitted. You may copy insights and summaries generated by the chatbot for your business needs."
    },
    {
        "question": "Can I request schema or table details?",
        "answer": "We do not provide full schema or table dumps. However, you can ask administration for that information."
    }
]

# Add a large header with an icon above the expander
st.markdown("<h3 style='font-size:2.5rem; display:flex; align-items:center;'>Frequently Asked Questions ❓</h3>", unsafe_allow_html=True)

with st.expander("See all FAQs", expanded=False):
    for faq in faqs:
        st.subheader(faq["question"])
        st.write(faq["answer"])

# Add a large header with an icon above the expander for maximizing tips
st.markdown("<h3 style='font-size:2.5rem; display:flex; align-items:center;'>Maximizing the Chatbot 💡</h3>", unsafe_allow_html=True)

with st.expander("Show example questions & tips", expanded=False):
    st.markdown("""
#### Example Questions
- What are the top sales trends for the last quarter?
- Show me conversion rates by gender and smoker status.
- Summarize the most common reasons for lost sales in March 2025.
- Provide a summary of customer feedback from recent call transcriptions.
- What is the average sum insured for female customers?
- Compare sales performance between brands for income protection products.
- List the most frequent objections raised in sales calls.
- Give me a breakdown of quotes and sales by product type.
- What are the key insights from Real Life Sale calls?
- Summarize call outcomes for OneChoice income protection no-sale cases.

#### Tips for Getting the Most Out of the Platform
- Be specific: The more details you provide (date range, product, brand), the more relevant the insights.
- Use business terms: Ask about KPIs, conversion rates, trends, or summaries.
- Leverage both SQL and transcription data: Ask for both quantitative (numbers, rates) and qualitative (call summaries, reasons) insights.
- Ask for Markdown summaries: All responses are formatted for easy copy-paste into reports or dashboards.
- Respect data boundaries: The chatbot cannot provide raw data or exports, but will always deliver actionable summaries.
- Try combining filters (e.g., by product, brand, and time period) for deeper insights.
- If unsure, start with a broad question and then ask follow-ups to drill down.
- Use the chatbot to summarize, compare, and interpret—not just to retrieve numbers.
- Review disclaimers for data coverage periods to ensure your queries are within available data ranges.
""")
