import os
from dotenv import load_dotenv

load_dotenv()

AZURE_API_KEY_AQMAGENTICOS = os.getenv("AZURE_OPENAI_API_KEY_AQMAGENTICOS")
AZURE_ENDPOINT_AQMAGENTICOS = os.getenv("AZURE_OPENAI_ENDPOINT_AQMAGENTICOS")
AZURE_DEPLOYMENT_O3 = "o3-mini"
AZURE_API_VERSION = "2024-12-01-preview"
AZURE_OPENAI_DEPLOYMENT_ID_AQMAGENTICOS = os.getenv("AZURE_OPENAI_DEPLOYMENT_ID_AQMAGENTICOS")
AZURE_OPENAI_API_VERSION_AQMAGENTICOS = os.getenv("AZURE_OPENAI_API_VERSION_AQMAGENTICOS")
TIMEZONE = "Australia/Sydney"
AZURE_AI_SEARCH_ENDPOINT=os.getenv("AZURE_AI_SEARCH_ENDPOINT")
AZURE_AI_SEARCH_API_KEY=os.getenv("AZURE_AI_SEARCH_API_KEY")
